version: '1'
services:
  ############################################
  ############### Postgres SQL ############### 
  ############################################ 
  postgres:
    build: ./docker/postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: thiennguyen
      POSTGRES_PASSWORD: thiennguyen
      POSTGRES_DB: test

    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "30m"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d test -U thiennguyen"] 
      timeout: 45s
      interval: 10s
      retries: 10

    networks:
      - infra-network

networks:
  infra-network:
    name: infra-network